EMAIL_HOST= # you can use https://mailtrap.io/
EMAIL_PORT= # you can use https://mailtrap.io/
EMAIL_USER= # you can use https://mailtrap.io/
EMAIL_PASS= # you can use https://mailtrap.io/
APP_MODE=development #or production
DATABASE_URL="mysql://...."
REDIS_HOST=redis
REDIS_PORT=6379
QUEUE_PREFIX=queue1
